theme: jekyll-theme-dinky
Title: One Step At The Time
Description: A place where to run a share projects relate to Science, football, Data, Statistics in not particular order. Please feel free to bookmark this repo to keep an eye in the development. 
logo: https://github.com/aliwualk/One-Step-at-a-Time/blob/master/Onstep2.png?raw=true
