theme: jekyll-theme-minimal
Title: One Step At The Time
Description: A place where to run a share projects relate to Science, football, Data, Statistics in not particular order. Please feel free to bookmark this repo to keep an eye in the development. 
logo: https://raw.githubusercontent.com/aliwualk/onestep/master/Onestep2.png
